<sdf xmlns:xacro="http://dd">
    <xacro:property name="width" value=".2" />
    <xacro:property name="bodylen" value=".6" />
    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${2*width}" length="${bodylen}" />
            </geometry>
            <material name="blue">
                <color rgba="0 0 .8 1" />
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${width}" length="${bodylen}" />
            </geometry>
        </collision>
    </link>
</sdf>